//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlackSoundDAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BlackSoundEntities : DbContext
    {
        public BlackSoundEntities()
            : base("name=BlackSoundEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<artistTable> artistTable { get; set; }
        public virtual DbSet<playlistTable> playlistTable { get; set; }
        public virtual DbSet<songTable> songTable { get; set; }
        public virtual DbSet<userTable> userTable { get; set; }
    }
}
